format_version: 10
pipelines:
  pipelineA:
    group: MyGroup
    materials:
      git:
        url: https://github.com/my/repo.git
        branch: main
    stages:
      - build:
          jobs:
            - build-job:
                tasks:
                  - exec:
                      command: echo
                      arguments: ["Building Pipeline A"]