format_version: 10
pipelines:
  expense-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/raghudevopsb79/expense-terraform
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: apply }
          approval: {type: manual}
          jobs:
            terraform-init:
              tasks:
                - exec: { command: echo, arguments: [ "terraform","init"] }
            terraform-plan:
              tasks:
                - exec: { command: echo, arguments: [ "terraform","plan" ] }
            terraform-apply:
              tasks:
                - exec: { command: echo, arguments: [ "terraform","apply" ] }

      - PROD:
          fetch_materials: true
          environment_variables: { env: prod, action: apply }
          jobs:
            terraform:
              tasks:
                - exec: { command: echo , arguments: [ "run.sh"] }


