format_version: 10
pipelines:
  parallel-job:
    group: Parallel
    label_template: ${COUNT}
    display_order: -1
    environment_variables: { env: pipeline-level, action: apply }
    materials:
      git-a66247d:
        git: https://github.com/RoboShop1/System_commands.git
        shallow_clone: true
        auto_update: true
        branch: main
        destination: app
    stages:
      - DEV:
          fetch_materials: true
          clean_workspace: true
          approval: {type: manual}
          environment_variables: { env: dev, action: apply }
          jobs:
            parallel-1:
              tasks:
                - exec: { command: echo, arguments: ["name=${env}"] }
                - exec: { command: printenv}

      - PROD:
          fetch_materials: true
          approval: {type: manual, allow_only_on_success: true}
          environment_variables: { env: stage-level, action: apply }
          jobs:
            job1:
              tasks:
               - exec: { command: printenv}
