format_version: 10
pipelines:
  parallel-job:
    group: Parallel
    label_template: ${COUNT}
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/RoboShop1/System_commands.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: apply }
          approval: {type: manual}
          jobs:
            parallel-1:
              tasks:
                - exec: { command: echo, arguments: ["task-1"] }
                - exec: { command: echo, arguments: ["task-2"] }
                - exec: { command: echo, arguments: ["task-3"] }

            parallel-2:
              tasks:
                - exec: { command: echo, arguments: ["task-1"] }
                - exec: { command: echo, arguments: ["task-2"] }
            parallel-3:
              tasks:
                - exec: { command: echo, arguments: ["task-1"] }
                - exec: { command: echo, arguments: ["task-2"] }

      - PROD:
          fetch_materials: true

          approval: {type: manual, allow_only_on_success: true}
          environment_variables: { env: prod, action: apply }
          jobs:
            job1:
              tasks:
                - exec: { command: echo , arguments: ["This is prod-env"] }
