format_version: 10
pipelines:
  deploy-dev:
    group: CD    # Group Name is IMP
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pipelines:                         # We can give any name
        pipeline: build-pipeline         # This has to be matched #
        stage: Image-Build               # Stage also matches from pipelineA
        auto_update: true
    stages:
      - Deploy:
          fetch_materials: true
          environment_variables: { env: dev, action: apply }
          jobs:
            deploy:
              tasks:
                - exec: { command: echo, arguments: ["Deploying into Dev Env"] }

      - sanityCheck:
          fetch_materials: true
          approval: {type: manual, allow_only_on_success: true}
          environment_variables: { env: dev, action: apply }
          jobs:
            deploy:
              tasks:
                - exec: { command: echo, arguments: [ "Performing sanityCheck..." ] }