format_version: 10

pipelines:
  sample-echo-pipeline:
    group: demo
    materials:
      git:
        url: https://github.com/RoboShop1/gocd-samples.git
        branch: main
    template: advanced-echo-template1