format_version: 10
pipelines:
  sample-echo-pipeline:
    group: demo
    materials:
      git-a66247d:
        git: https://github.com/RoboShop1/System_commands.git
        shallow_clone: true
        auto_update: true
        branch: main
        destination: app
    template: advanced-echo-template1
    parameters:
      NAME: "chaitu"