format_version: 10

templates:
  - name: deployment-template
    parameters:
      - name: app_name
      - name: deploy_env
    stages:
      - name: deploy
        jobs:
          - name: deploy-job
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "Deploying {{ app_name }} to {{ deploy_env }}"

pipelines:
  - name: app-production
    template: deployment-template
    parameters:
      app_name: "my-app"
      deploy_env: "production"

  - name: app-staging
    template: deployment-template
    parameters:
      app_name: "my-app"
      deploy_env: "staging"

environments:
  - name: production
    pipelines:
      - app-production
  - name: staging
    pipelines:
      - app-staging