format_version: 10
pipelines:
  pipeline-B:
    group: PipelineDependency # Group Name is IMP
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pipeline-A:
        pipeline: pipelineA
        stage: DEV
        auto_update: true
      git-a66247d:
        git: https://github.com/raghudevopsb79/expense-terraform
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: apply }
          jobs:
            pipeline-B:
              tasks:
                - exec: { command: echo, arguments: ["pipeline-B"] }