format_version: 10
pipelines:
  pipeline-B:
    group: PipelineDependency # Group Name is IMP
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      pipeline-A:
        pipeline: pipeline-A
        stage: DEV
        auto_update: true
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: apply }
          approval: { type: manual }
          jobs:
            pipeline-B:
              tasks:
                - exec: { command: echo, arguments: ["pipeline-B"] }